---- Updated definition for core.v_flows_pivot
--CREATE OR REPLACE VIEW core.v_flows_pivot AS
--SELECT
--    sku_id,
--    merchant_id,
--    sum(CASE WHEN direction = 'inflow'::text AND category_code = 'merchant_repayment'::text THEN signed_amount ELSE 0::numeric END) AS amount_received,
--    sum(CASE WHEN category_code = 'admin_fee'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS admin_fee_paid,
--    sum(CASE WHEN category_code = 'mgmt_fee'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS management_fee_paid,
--    sum(CASE WHEN category_code = 'int_diff'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS interest_difference_paid,
--    sum(CASE WHEN category_code = 'sr_prin'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS sr_principal_paid,
--    sum(CASE WHEN category_code = 'sr_int'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS sr_interest_paid,
--    sum(CASE WHEN category_code = 'jr_prin'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS jr_principal_paid,
--    sum(CASE WHEN category_code = 'jr_int'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS jr_interest_paid,
--    sum(CASE WHEN category_code = 'spar'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS spar_paid,
--    sum(CASE WHEN category_code = 'fh_add_admin_fee'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS additional_admin_fee_paid,
--    sum(CASE WHEN category_code = 'senior_add_investor_interest'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS sr_add_interest_paid,
--    sum(CASE WHEN category_code = 'junior_add_investor_interest'::text AND direction = 'outflow'::text THEN -signed_amount ELSE 0::numeric END) AS jr_add_interest_paid
--   FROM core.mv_va_txn_flows
--  GROUP BY sku_id, merchant_id;